---

all:
  children:
    physical:
      hosts:
        localhost: 
          ansible_host: 127.0.0.1
        server0002:
          ansible_host: 192.168.3.132
          ansible_user: "user"
          remote_user: "user"
          ansible_become_user: "root"
          ansible_become_pass: ""
    virtual:
      hosts:
      vars:
        weitere_pakete:
          - open-vm-tools
  vars:
    ansible_user: "root"
    zeilen_vergangenheit: 100000
    zeilen_vergangenheitsdatei: 200000
    sshd_root_login: "yes" # no, prohibited-password, yes
    sshd_port: 2048
    ssh_port: 2048
    ansible_python_interpreter: /usr/bin/python3
    become: "yes"
