---

all:
  children:
    physical:
      hosts:
        localhost: 
          ansible_host: 127.0.0.1

    virtual:
      hosts:
      vars:
        weitere_pakete:
          - open-vm-tools
  vars:
    ansible_user: "root"
    zeilen_vergangenheit: 100000
    zeilen_vergangenheitsdatei: 200000
    sshd_root_login: "yes" # no, prohibited-password, yes
    sshd_port: 2048
    ssh_port: 2048
    ansible_python_interpreter: /usr/bin/python3
